;;; -*- coding: utf-8-unix; mode: scheme; -*-
(import (scheme base) (scheme char)
        (scheme cxr) (scheme eval) (scheme file) (scheme inexact)
        (scheme load) (scheme process-context) (scheme read)
        (scheme repl) (scheme time) (scheme write))
;; (import (scheme case-lambda))
;; (import (scheme complex))
;; (import (scheme lazy))
(import (scheme list) (scheme vector) (scheme sort) (scheme set)
        (scheme charset) (scheme hash-table)
        (scheme comparator)
        (scheme regex) (scheme division)
        (scheme bitwise) (scheme fixnum) (scheme flonum)
        (scheme show))
;; (import (scheme ilist))
;; (import (scheme rlist))
;; (import (scheme ideque))
;; (import (scheme text))
;; (import (scheme generator))
;; (import (scheme lseq))
;; (import (scheme stream))
;; (import (scheme box))
;; (import (scheme list-queue))
;; (import (scheme ephemeron))
;; (import (scheme mapping))
;; (import (scheme bytevector))

(display "Hello, world!")
(newline)
(display "Good-bye, human!")
(newline)
