#!/bin/bash
# -*- coding: utf-8-unix; mode: shell-script; -*-

### # 概要
###

cd $(dirname $0)

../bin/NUMBERING

# -*- Local Variables: -*-
# -*- indent-tabs-mode: nil -*-
# -*- sh-basic-offset: 2 -*-
# -*- End: -*-
