#!/bin/bash
# -*- coding: utf-8-unix; mode: shell-script; sh-basic-offset: 2 -*-

### # 概要
###

cd $(dirname $0)

base="TEST-"
keta=2
ext=css

wild="${base}$(printf '[0-9]%.0s' $(seq 1 $keta)).${ext}"

ls ${wild} &> /dev/null

if [ $? -ne 0 ] ; then
  echo ${base}$(printf "%0${keta}d" 1).${ext}
else
  lastfile=$(ls ${wild} | tail -1)
  if [[ "$lastfile" =~ ^${base}([0-9]{${keta}}).${ext}$ ]] ; then
    num=${BASH_REMATCH[1]}
    echo ${base}$(printf "%0${keta}d" $(expr $num + 1)).${ext}
  fi
fi
